#!/usr/bin/env python

import chess.pgn
import chess
import argparse
import sys

parser = argparse.ArgumentParser(
    description='Convert a pgn with chess positions into a csv file for import into anki')
parser.add_argument('--pgn', help='filename of pgn')
parser.add_argument('--depth', help='int denoting how deep to go from root node')
parser.add_argument('--player', help='player, either White or Black')


args = parser.parse_args()

if(args.pgn == None or args.player == None):
    parser.print_usage()
    sys.exit(1)

filename_pgn = args.pgn
filename_out = "import_anki.csv"
depth = 200
if(args.depth != None):
    depth = int(args.depth)
player_input = args.player

pgn = open(filename_pgn)
game = chess.pgn.read_game(pgn)

node = game

lines = []
player = chess.WHITE

if(player_input == "Black" or player_input == "black" or player_input == "BLACK"):
    player = chess.BLACK
flip_board = True

def node2png(node, depth, maxdepth):
    global card_list
    global player
    global flip_board
    if not node.is_end() and not depth >= maxdepth:
        trn = node.board().turn
        if(trn == player):
            # first print the current node
            fen_string = node.board().fen()
            san = "?"
            if not node.is_end():
                child = node.variation(0)
                move = child.move
                if move != None:
                    san = node.board().san(move)
            # add link for textfile
            lines.append("[fen]"+fen_string+"[/fen],"+san) 
        for node_i in node.variations:
            node2png(node_i, depth+1, maxdepth)


node2png(node, 0, depth)

pgn.close()

f = open(filename_out, "w")
for line in lines:
    f.write(line)
    f.write("\n")
f.close()
